#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale $HOME/Pictures/wallpapers/solarized4.jpg
$HOME/.config/polybar/launch.sh
dunst &
picom --experimental-backends -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color \#5e81aa
bspc config normal_border_color  \#565f99

bspc config window_gap           8

bspc config split_ratio          0.54
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^3'
bspc rule -a Chromium desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


